version: '3'
services:
  app:
    image: python:3.12
    volumes:
      - .:/app
    command: bash -c "pip install fastapi uvicorn && uvicorn main:app --host 0.0.0.0 --port 8888"
    network_mode: host
    ports:
      - 8888:8888
